// generated by servers_generate.go; DO NOT EDIT

package transport

// These transports are supported by CoreDNS.
const (
	TLS   = "tls"
	HTTPS = "https"
	GRPC  = "grpc"
	DNS   = "dns"
)

// Port numbers for the various transports.
const (
	// Port is the default port for DNS
	Port = "53"

	TLSPort   = "853"
	HTTPSPort = "443"
	GRPCPort  = "443"
	DNSPort   = "53"
)
