// generated by servers_generate.go; DO NOT EDIT

package dnsserver

// Servers are registered in the order they are specified in the server.cfg
//
import (
	"github.com/coredns/caddy"
	"github.com/coredns/coredns/plugin/pkg/transport"
)

func init() {

	RegisterTransportServer(transport.TLS, transport.TLSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServerTLS(addr, group)
	})

	RegisterTransportServer(transport.HTTPS, transport.HTTPSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServerHTTPS(addr, group)
	})

	RegisterTransportServer(transport.GRPC, transport.GRPCPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServergRPC(addr, group)
	})

	RegisterTransportServer(transport.DNS, transport.DNSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServer(addr, group)
	})
}
