// generated by servers_generate.go; DO NOT EDIT

package dnsserver

// Servers are registered in the order they are specified in the server.cfg
//
import (
	"github.com/coredns/caddy"
)

const (
	GRPC     = "grpc"
	GRPCPort = "443"

	DNS     = "dns"
	DNSPort = "53"

	TLS     = "tls"
	TLSPort = "853"

	HTTPS     = "https"
	HTTPSPort = "443"
)

func init() {

	RegisterTransportServer(GRPC, GRPCPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServergRPC(addr, group)
	})

	RegisterTransportServer(DNS, DNSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServer(addr, group)
	})

	RegisterTransportServer(TLS, TLSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServerTLS(addr, group)
	})

	RegisterTransportServer(HTTPS, HTTPSPort, func(addr string, group []*Config) (caddy.Server, error) {
		return NewServerHTTPS(addr, group)
	})
}
